name: LCARS Status Bot

# Every 2 hours, at :15 (less queue congestion)
on:
  schedule:
    - cron: '15 */2 * * *'
  workflow_dispatch:   # manual trigger

jobs:
  post:
    runs-on: ubuntu-latest
    steps:
      # -------------------------------------------------
      # 1. Generate a random LCARS message with ship name
      # -------------------------------------------------
      - name: Build LCARS tweet
        run: |
          # ---- Starfleet ship registry (add as many as you like) ----
          SHIPS=(
            "USS Enterprise NCC-1701-D"
            "USS Voyager NCC-74656"
            "USS Defiant NX-74205"
            "USS Discovery NCC-1031"
            "USS Cerritos NCC-75567"
            "USS Protostar NX-76884"
            "USS Excelsior NCC-2000"
            "USS Reliant NCC-1864"
            "USS Stargazer NCC-2893"
            "USS Titan NCC-80102"
          )

          # ---- LCARS status templates (use {ship} and {ts}) ----
          TEMPLATES=(
            "LCARS SYSTEM LOG [{ts}] — {ship} sensor grid recalibration complete. Quantum flux deviation within 0.0003%. Deep-space telemetry nominal."
            "LCARS ALERT [{ts}] — {ship} detects subspace anomaly at bearing 234.7 mark 12. Signature unmatched."
            "LCARS STATUS [{ts}] — {ship} warp core efficiency 99.7%. Antimatter containment stable. Life support optimal."
            "LCARS DIAGNOSTIC [{ts}] — {ship} holodeck matrix drift corrected. Photonic resonance restored."
            "LCARS LOG [{ts}] — {ship} long-range probe 47-B reports intermittent tachyon echoes. Source unknown."
            "LCARS REPORT [{ts}] — {ship} shield harmonics re-modulated. Defensive grid integrity 100%."
            "LCARS UPDATE [{ts}] — {ship} stellar cartography update in progress. 12 new Class-M signatures added."
            "LCARS NOTICE [{ts}] — {ship} transporter buffer integrity verified. Pattern degradation 0.000%."
            "LCARS SCAN [{ts}] — {ship} passive sweep detects encrypted burst. Origin: Sector 001."
            "LCARS CORE [{ts}] — {ship} main computer core temperature 21.3°C. Redundancy online."
          )

          # ---- Random selection -------------------------------------------------
          SHIP=$(shuf -e "${SHIPS[@]}" -n1)
          TEMPLATE=$(shuf -e "${TEMPLATES[@]}" -n1)
          TS=$(date -u +"%Y-%m-%d %H:%M:%S")UTC

          TEXT="${TEMPLATE//\{ship\}/$SHIP}"
          TEXT="${TEXT//\{ts\}/$TS}"

          echo "Generated tweet:"
          echo "$TEXT"
          echo "TWEET_TEXT<<EOF" >> $GITHUB_ENV
          echo "$TEXT" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      # -------------------------------------------------
      # 2. Post to X/Twitter (curl only)
      # -------------------------------------------------
      - name: Send tweet
        env:
          BEARER: ${{ secrets.X_BEARER_TOKEN }}
        run: |
          if [ -z "$BEARER" ]; then
            echo "Error: X_BEARER_TOKEN secret missing!"
            exit 1
          fi

          PAYLOAD=$(jq -n --arg txt "$TWEET_TEXT" '{"text":$txt}')
          RESPONSE=$(curl -s -w "\n%{http_code}" -X POST \
            "https://api.twitter.com/2/tweets" \
            -H "Authorization: Bearer $BEARER" \
            -H "Content-Type: application/json" \
            -d "$PAYLOAD")

          HTTP=$(echo "$RESPONSE" | tail -n1)
          BODY=$(echo "$RESPONSE" | sed '$d')

          echo "HTTP $HTTP"
          echo "Response: $BODY"

          if [ "$HTTP" = "201" ]; then
            ID=$(echo "$BODY" | jq -r '.data.id')
            echo "Success: Tweet posted! https://x.com/i/status/$ID"
          else
            echo "Error: Failed to post (HTTP $HTTP)"
            exit 1
          fi
