name: Starfleet HR Complaint

on:
  schedule:
    - cron: '0 */4 * * *'     # Checks every 4 hours
  workflow_dispatch:

jobs:
  post:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Tweepy
        run: pip install tweepy

      - name: Run Script with Secrets
        env:
          CONSUMER_KEY: ${{ secrets.CONSUMER_KEY }}
          CONSUMER_SECRET: ${{ secrets.CONSUMER_SECRET }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
        run: |
          # === Print secrets into Python script (THIS IS THE KEY) ===
          cat > post_complaint.py << 'PY'
          import os
          import tweepy, random
          from datetime import datetime, timedelta, timezone

          # === Secrets injected from GitHub (via env + print) ===
          ck = """$CONSUMER_KEY"""
          cs = """$CONSUMER_SECRET"""
          at = """$ACCESS_TOKEN"""
          ats = """$ACCESS_TOKEN_SECRET"""

          # Strip empty lines or quotes
          ck = ck.strip()
          cs = cs.strip()
          at = at.strip()
          ats = ats.strip()

          if not all([ck, cs, at, ats]):
              print("ERROR: One or more secrets are missing or empty")
              exit(1)

          print("All secrets loaded successfully")

          # === OAuth 1.0a ===
          auth = tweepy.OAuth1UserHandler(ck, cs, at, ats)
          api = tweepy.API(auth)

          try:
              user = api.verify_credentials()
              print(f"Authenticated as @{user.screen_name}")
          except Exception as e:
              print(f"Auth failed: {e}")
              exit(1)

          # === Complaints ===
          complaints = [
              "Anonymous: The replicator gave me decaf AGAIN.",
              "Anonymous: Phaser on 'stun' feels like a hug.",
              "Anonymous: Holodeck vacation → Klingon blood oath.",
              "Anonymous: Turbolift stopped on 47 decks. Again.",
              "Anonymous: Counselor says I need 'emotional recalibration'.",
              "Anonymous: Door squeaks. Engineering: 'It's ambiance.'",
              "Anonymous: Replicated coffee tastes like warp plasma.",
              "Anonymous: Badge fell off during red alert.",
              "Anonymous: Captain's log: 99% dramatic pauses.",
              "Anonymous: Hypospray hurts more than the injury."
          ]

          # === 17-hour check ===
          should_post = True
          try:
              tweets = api.user_timeline(count=1)
              if tweets:
                  last = tweets[0].created_at.replace(tzinfo=timezone.utc)
                  hours = (datetime.now(timezone.utc) - last).total_seconds() / 3600
                  if hours < 17:
                      should_post = False
                      print(f"Last post {hours:.1f}h ago → SKIP")
                  else:
                      print(f"Last post {hours:.1f}h ago → POST")
              else:
                  print("No tweets → FIRST POST")
          except Exception as e:
              print(f"Timeline error: {e} → POST anyway")

          # === Post ===
          if should_post:
              msg = random.choice(complaints)
              try:
                  api.update_status(msg)
                  print(f"POSTED: {msg}")
              except Exception as e:
                  print(f"Post failed: {e}")
          else:
              print("Post skipped (17h rule)")
          PY

          # === Inject actual secret values into the script ===
          sed -i "s|\$CONSUMER_KEY|$CONSUMER_KEY|g" post_complaint.py
          sed -i "s|\$CONSUMER_SECRET|$CONSUMER_SECRET|g" post_complaint.py
          sed -i "s|\$ACCESS_TOKEN|$ACCESS_TOKEN|g" post_complaint.py
          sed -i "s|\$ACCESS_TOKEN_SECRET|$ACCESS_TOKEN_SECRET|g" post_complaint.py

          # === Run it ===
          python post_complaint.py
