name: Starfleet HR Complaint Poster

on:
  schedule:
    - cron: '0 */4 * * *'  # Every 4 hours
  workflow_dispatch:

jobs:
  post-complaint:
    runs-on: ubuntu-latest
    env:
      CONSUMER_KEY: ${{ secrets.CONSUMER_KEY }}
      CONSUMER_SECRET: ${{ secrets.CONSUMER_SECRET }}
      ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Tweepy
        run: pip install tweepy

      - name: Validate Secrets & Post
        run: |
          python - <<'PY'
          import tweepy
          import random
          from datetime import datetime, timedelta, timezone
          import os

          # === Load and validate secrets ===
          ck = os.getenv('CONSUMER_KEY')
          cs = os.getenv('CONSUMER_SECRET')
          at = os.getenv('ACCESS_TOKEN')
          ats = os.getenv('ACCESS_TOKEN_SECRET')

          missing = [k for k, v in [('CONSUMER_KEY', ck), ('CONSUMER_SECRET', cs), 
                                    ('ACCESS_TOKEN', at), ('ACCESS_TOKEN_SECRET', ats)] if not v]
          if missing:
              print(f"ERROR: Missing secrets: {', '.join(missing)}")
              print("Go to repo Settings > Secrets and add them.")
              exit(1)

          print("All secrets loaded.")

          # === OAuth 1.0a Authentication ===
          try:
              auth = tweepy.OAuth1UserHandler(ck, cs, at, ats)
              api = tweepy.API(auth)
              # Test auth
              api.verify_credentials()
              print("Authentication successful!")
          except Exception as e:
              print(f"Authentication FAILED: {e}")
              print("Check your API keys at https://developer.x.com")
              exit(1)

          # === Starfleet HR Complaints ===
          complaints = [
              "Anonymous: The replicator gave me decaf AGAIN.",
              "Anonymous: My phaser is set to 'stun' but it feels more like 'mild annoyance'.",
              "Anonymous: The holodeck keeps glitching and turning my vacation into a Klingon opera.",
              "Anonymous: Why does the turbolift always stop at every deck when I'm in a hurry?",
              "Anonymous: The ship's counselor is too empathetic; now I feel bad for complaining.",
              "Anonymous: Engineering won't fix the squeaky door in my quarters—claims it's 'ambient noise'.",
              "Anonymous: The food synthesizer only produces bland rations; where's the flavor variety?",
              "Anonymous: My communicator badge fell off during a red alert—embarrassing!",
              "Anonymous: The captain's logs are too dramatic; can we tone down the narration?",
              "Anonymous: Sickbay's hyposprays sting more than a Tribble bite.",
          ]

          # === Check last tweet (safe fallback) ===
          should_post = True
          try:
              tweets = api.user_timeline(count=1, tweet_mode='extended')
              if tweets:
                  last_time = tweets[0].created_at.replace(tzinfo=timezone.utc)
                  since_last = datetime.now(timezone.utc) - last_time
                  if since_last < timedelta(hours=17):
                      should_post = False
                      print(f"Last post {since_last.total_seconds()//3600:.1f}h ago. Skipping.")
                  else:
                      print(f"Last post {since_last.total_seconds()//3600:.1f}h ago. Posting!")
              else:
                  print("No tweets found. First post!")
          except Exception as e:
              print(f"Could not check timeline: {e}")
              print("Will post anyway (safe fallback).")

          # === Post if needed ===
          if should_post:
              complaint = random.choice(complaints)
              try:
                  api.update_status(complaint)
                  print(f"SUCCESS: Posted → {complaint}")
              except Exception as e:
                  print(f"Failed to post: {e}")
          else:
              print("Post skipped.")
          PY
