name: Starfleet HR Complaint

on:
  schedule:
    - cron: '0 */4 * * *'     # ← Checks every 4 hours
  workflow_dispatch:

jobs:
  post:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Tweepy
        run: pip install tweepy

      - name: Write & Run Script
        env:
          CONSUMER_KEY: ${{ secrets.CONSUMER_KEY }}
          CONSUMER_SECRET: ${{ secrets.CONSUMER_SECRET }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
        run: |
          cat > post_complaint.py << 'PYEOF'
          import tweepy, random, os
          from datetime import datetime, timedelta, timezone

          # Load secrets
          ck = os.getenv('CONSUMER_KEY')
          cs = os.getenv('CONSUMER_SECRET')
          at = os.getenv('ACCESS_TOKEN')
          ats = os.getenv('ACCESS_TOKEN_SECRET')

          if not all([ck, cs, at, ats]):
              print("ERROR: Missing secrets")
              exit(1)

          print("Secrets OK")

          # OAuth 1.0a
          auth = tweepy.OAuth1UserHandler(ck, cs, at, ats)
          api = tweepy.API(auth)
          try:
              user = api.verify_credentials()
              print(f"Logged in: @{user.screen_name}")
          except Exception as e:
              print(f"Auth failed: {e}")
              exit(1)

          # Complaints
          complaints = [
              "Anonymous: The replicator gave me decaf AGAIN.",
              "Anonymous: Phaser on 'stun' = gentle pat.",
              "Anonymous: Holodeck vacation → Klingon blood oath.",
              "Anonymous: Turbolift stopped on EVERY deck.",
              "Anonymous: Counselor says I need 'anger management'.",
              "Anonymous: Door squeaks. Engineering: 'It's ambiance.'",
              "Anonymous: Replicated coffee tastes like dilithium runoff.",
              "Anonymous: Badge fell off during red alert. Again.",
              "Anonymous: Captain's log: 90% dramatic stare.",
              "Anonymous: Hypospray hurts more than the phaser hit."
          ]

          # === 17-HOUR RULE ===
          should_post = True
          try:
              tweets = api.user_timeline(count=1)
              if tweets:
                  last = tweets[0].created_at.replace(tzinfo=timezone.utc)
                  hours_ago = (datetime.now(timezone.utc) - last).total_seconds() / 3600
                  if hours_ago < 17:
                      should_post = False
                      print(f"Last post {hours_ago:.1f}h ago → SKIP")
                  else:
                      print(f"Last post {hours_ago:.1f}h ago → POST")
              else:
                  print("No tweets → FIRST POST")
          except Exception as e:
              print(f"Timeline error: {e} → POST anyway")

          # Post
          if should_post:
              msg = random.choice(complaints)
              try:
                  api.update_status(msg)
                  print(f"POSTED: {msg}")
              except Exception as e:
                  print(f"Post failed: {e}")
          else:
              print("Post skipped (17h rule)")
          PYEOF

          python post_complaint.py
