name: Starfleet HR Complaint

on:
  schedule:
    - cron: '0 */4 * * *'
  workflow_dispatch:

jobs:
  post:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Tweepy
        run: pip install tweepy

      - name: Post Complaint
        env:
          CONSUMER_KEY: ${{ secrets.CONSUMER_KEY }}
          CONSUMER_SECRET: ${{ secrets.CONSUMER_SECRET }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
        run: |
          cat > post_complaint.py <<'PY'
import tweepy
import random

# === Secrets will be injected below ===
CONSUMER_KEY = ""
CONSUMER_SECRET = ""
ACCESS_TOKEN = ""
ACCESS_TOKEN_SECRET = ""

# === Validate ===
if not all([CONSUMER_KEY, CONSUMER_SECRET, ACCESS_TOKEN, ACCESS_TOKEN_SECRET]):
    print("ERROR: One or more secrets are missing")
    exit(1)

print("All secrets loaded")

# === OAuth 1.0a ===
auth = tweepy.OAuth1UserHandler(CONSUMER_KEY, CONSUMER_SECRET, ACCESS_TOKEN, ACCESS_TOKEN_SECRET)
api = tweepy.API(auth)
user = api.verify_credentials()
print(f"Authenticated as @{user.screen_name}")

# === Complaints ===
complaints = [
    "Anonymous: The replicator gave me decaf AGAIN.",
    "Anonymous: Phaser on 'stun' feels like a hug.",
    "Anonymous: Holodeck vacation → Borg cube.",
    "Anonymous: Turbolift stopped on 47 decks.",
    "Anonymous: Counselor says I need therapy.",
    "Anonymous: Door squeaks. Engineering: 'It's ambiance.'",
    "Anonymous: Replicated coffee tastes like warp coolant.",
    "Anonymous: Badge fell off during red alert.",
    "Anonymous: Captain's log: 99% dramatic pauses.",
    "Anonymous: Hypospray hurts more than the injury."
]

msg = random.choice(complaints)
api.update_status(msg)
print(f"POSTED: {msg}")
PY

          # === Inject secrets safely using printf and sed ===
          printf '%s\n' "s|CONSUMER_KEY = \"\"|CONSUMER_KEY = \"${CONSUMER_KEY}\"|g" > replace.sed
          printf '%s\n' "s|CONSUMER_SECRET = \"\"|CONSUMER_SECRET = \"${CONSUMER_SECRET}\"|g" >> replace.sed
          printf '%s\n' "s|ACCESS_TOKEN = \"\"|ACCESS_TOKEN = \"${ACCESS_TOKEN}\"|g" >> replace.sed
          printf '%s\n' "s|ACCESS_TOKEN_SECRET = \"\"|ACCESS_TOKEN_SECRET = \"${ACCESS_TOKEN_SECRET}\"|g" >> replace.sed

          sed -i -f replace.sed post_complaint.py

          # === Run ===
          python post_complaint.py
