name: Starfleet HR Complaint

on:
  schedule:
    - cron: '0 */4 * * *'     # Checks every 4 hours
  workflow_dispatch:

jobs:
  post:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Tweepy
        run: pip install tweepy

      - name: Inject Secrets & Run
        env:
          CONSUMER_KEY: ${{ secrets.CONSUMER_KEY }}
          CONSUMER_SECRET: ${{ secrets.CONSUMER_SECRET }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
        run: |
          # === Export so sed can see them ===
          export CONSUMER_KEY="$CONSUMER_KEY"
          export CONSUMER_SECRET="$CONSUMER_SECRET"
          export ACCESS_TOKEN="$ACCESS_TOKEN"
          export ACCESS_TOKEN_SECRET="$ACCESS_TOKEN_SECRET"

          # === Create Python script with placeholders ===
          cat > post_complaint.py << 'PY'
          import tweepy, random
          from datetime import datetime, timedelta, timezone

          # === PLACEHOLDERS (will be replaced) ===
          ck = "PLACEHOLDER_CONSUMER_KEY"
          cs = "PLACEHOLDER_CONSUMER_SECRET"
          at = "PLACEHOLDER_ACCESS_TOKEN"
          ats = "PLACEHOLDER_ACCESS_TOKEN_SECRET"

          # === Replace placeholders with real values ===
          import os
          ck = ck.replace("PLACEHOLDER_CONSUMER_KEY", os.getenv('CONSUMER_KEY', ''))
          cs = cs.replace("PLACEHOLDER_CONSUMER_SECRET", os.getenv('CONSUMER_SECRET', ''))
          at = at.replace("PLACEHOLDER_ACCESS_TOKEN", os.getenv('ACCESS_TOKEN', ''))
          ats = ats.replace("PLACEHOLDER_ACCESS_TOKEN_SECRET", os.getenv('ACCESS_TOKEN_SECRET', ''))

          if not all([ck, cs, at, ats]):
              print("ERROR: One or more secrets are missing or empty")
              exit(1)

          print("All secrets loaded")

          # === OAuth 1.0
