name: Starfleet HR Complaint

on:
  schedule:
    - cron: '0 */4 * * *'
  workflow_dispatch:

jobs:
  post:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Tweepy
        run: pip install tweepy

      - name: Export Secrets & Run
        env:
          CONSUMER_KEY: ${{ secrets.CONSUMER_KEY }}
          CONSUMER_SECRET: ${{ secrets.CONSUMER_SECRET }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
        run: |
          export CONSUMER_KEY="$CONSUMER_KEY"
          export CONSUMER_SECRET="$CONSUMER_SECRET"
          export ACCESS_TOKEN="$ACCESS_TOKEN"
          export ACCESS_TOKEN_SECRET="$ACCESS_TOKEN_SECRET"

          cat > post_complaint.py << 'PY'
          import tweepy, random, os
          from datetime import datetime, timedelta, timezone

          ck = os.getenv('CONSUMER_KEY')
          cs = os.getenv('CONSUMER_SECRET')
          at = os.getenv('ACCESS_TOKEN')
          ats = os.getenv('ACCESS_TOKEN_SECRET')

          if not all([ck, cs, at, ats]):
              print("ERROR: Secrets missing")
              exit(1)

          print("All secrets loaded")

          auth = tweepy.OAuth1UserHandler(ck, cs, at, ats)
          api = tweepy.API(auth)

          try:
              user = api.verify_credentials()
              print(f"Authenticated as @{user.screen_name}")
          except Exception as e:
              print(f"Auth failed: {e}")
              exit(1)

          complaints = [
              "Anonymous: The replicator gave me decaf AGAIN.",
              "Anonymous: Phaser on 'stun' = tickle.",
              "Anonymous: Holodeck vacation → Borg cube.",
              "Anonymous: Turbolift stopped on EVERY deck.",
              "Anonymous: Counselor says I need 'therapy'.",
              "Anonymous: Door squeaks. Engineering: 'It's ambiance.'",
              "Anonymous: Replicated coffee tastes like warp coolant.",
              "Anonymous: Badge fell off during red alert.",
              "Anonymous: Captain's log: 99% dramatic pauses.",
              "Anonymous: Hypospray hurts more than the injury."
          ]

          should_post = True
          try:
              tweets = api.user_timeline(count=1)
              if tweets:
                  last = tweets[0].created_at.replace(tzinfo=timezone.utc)
                  hours = (datetime.now(timezone.utc) - last).total_seconds() / 3600
                  if hours < 17:
                      should_post = False
                      print(f"Last post {hours:.1f}h ago → SKIP")
                  else:
                      print(f"Last post {hours:.1f}h ago → POST")
              else:
                  print("First tweet → POST")
          except Exception as e:
              print(f"Timeline error: {e} → POST anyway")

          if should_post:
              msg = random.choice(complaints)
              try:
                  api.update_status(msg)
                  print(f"POSTED: {msg}")
              except Exception as e:
                  print(f"Post failed: {e}")
          else:
              print("Post skipped")
          PY

          python post_complaint.py
